### ISSUE TITLE
End of Stream Signal

### ISSUE THREAD

**Issue by AnthumChris** [padenot/ringbuf.js#4]
Would it be helpful for `RingBuffer` to store an internal "end of stream" signal received by the producer to notify the consumer?  Or should that be managed externally?  For example, a cross-realm scenario could avoid async messaging by setting/getting the end flags:

```js
// main.js
[ numWritten, didAllWrite ] = ringBuffer.write(elements, isEnd)
```

```js
// worker.js
[ numRead, isEnd ] = ringBuffer.read(elements)

**Comment by padenot** [comment]
This is high level for this ring buffer. You want to either have a packet system where you can have arbitrary messages (like the parameter change examples), or have sentinel values in the audio stream that signal EOS.
