### ISSUE TITLE
Question about streaming from AudioWorkletProcessor

### ISSUE THREAD

**Issue by tinchoz49** [padenot/ringbuf.js#5]
Hey @padenot, how are you?

I want to get (in the main thread) the raw data of a microphone from a MediaStream. I think I could use your example but as the opposite flow. Does that make sense?

**Comment by padenot** [comment]
This is how I would do it as well. Make sure to have enough room in the ring buffer to handle the case where `setTimeout` and other scheduling APIs are throttled because the tab is in the background, and your code will only be called about once a second.

**Comment by tinchoz49** [comment]
Thank you
